apiVersion: v1
kind: Pod
metadata:
  name: pod-with-initcontainer
  labels:
    app: myapp
spec:
  containers:
    - name: main-container
      image: busybox
      command: ['sh', '-c', 'echo Inside the main-container! && sleep 36000']
  initContainers:
    - name: init-container-1
      image: busybox
      command: ['sh', '-c', 'echo Inside init-container-1 start; sleep 15;echo init-container-1 completed;']
    - name: init-container-2
      image: busybox
      command: ['sh', '-c', 'echo Inside init-container-2 start; sleep 15;echo init-container-2 completed;']