api:
  version: v1

server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  folder: ./logs

# Swagger.ui url:
#http://localhost:8080/swagger-ui.html

#Mongo
spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: sampledb
      
