apiVersion: v1
kind: Service
metadata:
  name: client-usermanagement-sc
spec:
  selector:
    app: usermanagement
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-cm
data:
  # property-like keys; each key maps to a simple value
  mongodbservice: "client-mongodb-sc"
  mongodbport: "27017"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement
  labels:
    app: usermanagement
spec:
  selector:
    matchLabels:
      app: usermanagement
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      #Always, OnFailure, and Never
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: wait
          image: "tiagoferreira2018/waitforit:latest"
          args:
            - /bin/sh
            - -c
            - /initcontainer/wait-for-it.sh "client-mongodb-sc:27017" -t 0
      containers:
        - name: usermanagement
          image: "tiagoferreira2018/usermngdemo:1.0-SNAPSHOT"
          #Always, IfNotPresent
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: usermanagement-cm
                  key: mongodbservice
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: usermanagement-cm
                  key: mongodbport
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}