api:
  version: v1

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  folder: ./logs

# Swagger.ui url:
#http://localhost:8080/swagger-ui.html

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

#Mongo
spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: sampledb
      
